import { describe, expect, it } from "vitest";
import { computeCommitment } from "./commitment";

const hex = (bytes: Uint8Array) =>
  Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");

const zeroSalt = new Uint8Array(32);
const onesSalt = new Uint8Array(32).fill(0x11);
const incSalt = Uint8Array.from({ length: 32 }, (_, i) => i);

// Ground truth generated by the Rust side:
// programs/acertana/src/lib.rs tests::commitment_test_vectors
// (anchor_lang::solana_program::keccak over the same preimages). Keep in sync.
const vectors: Array<[number, number, Uint8Array, string]> = [
  [0, 0, zeroSalt, "bf53adb76067fdab0d008aef3ad8b28bbb63c2ce4c2b63394ede73f01a70c865"],
  [9, 9, onesSalt, "a184b447732db82000bb9a63f2925a16cb9eb38abe40c3a8b1d50a05767e5a1b"],
  [2, 1, incSalt, "73539fcb8771b64bd066f8db16ffd2bae8ba804f7c91360b08632ed7f23fc1d3"],
];

describe("computeCommitment", () => {
  it.each(vectors)("matches Rust digest for (%i,%i)", (home, away, salt, expected) => {
    const digest = computeCommitment(home, away, salt);
    expect(digest).toHaveLength(32);
    expect(hex(digest)).toBe(expected);
  });

  it("rejects salt that is not 32 bytes", () => {
    expect(() => computeCommitment(1, 1, new Uint8Array(31))).toThrow(RangeError);
    expect(() => computeCommitment(1, 1, new Uint8Array(33))).toThrow(RangeError);
    expect(() => computeCommitment(1, 1, new Uint8Array(0))).toThrow(RangeError);
  });

  it("rejects non-integer or out-of-range goals", () => {
    for (const bad of [-1, 256, 1.5, NaN, Infinity]) {
      expect(() => computeCommitment(bad, 0, zeroSalt)).toThrow(RangeError);
      expect(() => computeCommitment(0, bad, zeroSalt)).toThrow(RangeError);
    }
  });
});
